### ISSUE TITLE
install error in nodejs v8

### ISSUE THREAD

**Issue by JennerChen** [sindresorhus/new-github-release-url#1]
install error when use nodejs v8, please change engines field to meet v8 
`error new-github-release-url@0.1.0: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.12.0"`

**Comment by sindresorhus** [comment]
This package requires Node.js 10 or later.

**Comment by Saeris** [comment]
Curious to know why there's a hard dependency on Node.js v10. I'm only just learning about this package because of it's usage in [@pika/pack](https://github.com/pikapkg/pack). A cursory glance at the code and the package dependencies doesn't shed any light on why this is necessary, except for maybe using ESM `import` syntax in `test.js`. Can open a PR if you don't have the bandwidth to make the changes right now.
